
@server_url=https://kd1.kuaihe.tech/ed/api/v1

@email=
@password=
@team_code=sgmd

###
# @name login
POST {{server_url}}/auth/login
Content-Type: application/json

{"email": "{{email}}", "password": "{{password}}"}

###
@jwtoken = {{login.response.body.data.token}}



###
# @name create_team
POST {{server_url}}/teams/
Authorization: Bearer {{jwtoken}}
Content-Type: application/json

{
    "code": "{{team_code}}", "name": "{{team_code}}", 
    "geo_longitude": 103.835, 
    "geo_latitude": 1.303, 
    "planner_service": {"code": "single"}, 
    "flex_form_data": {
        "fixed_horizon_flag": "1",
        "env_start_datetime": "2023-11-13T00:00:00",
        "horizon_start_datetime": "2023-11-13T08:01:01",
        "nbr_minutes_planning_windows_duration": 1440,

        "enable_skills": "1"
    }
}




###
# @name create_worker
POST {{server_url}}/workers/   HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
    "code": "w1", 
    "name": "w1",
    "team": {"code": "{{team_code}}"}, 
    "geo_longitude": 103.939, 
    "geo_latitude": 1.381, 
    "flex_form_data": {"area_code": "A", "capacity_volume": 0, "max_nbr_order": 0,"skills":"kitchen"}, 
    "business_hour": {
        "monday": [{"open": "0005", "close": "2330", "id": "a0", "isOpen": true}], 
        "tuesday": [{"open": "0005", "close": "2330", "id": "a1", "isOpen": true}], 
        "wednesday": [{"open": "0005", "close": "2330", "id": "a2", "isOpen": true}], 
        "thursday": [{"open": "0005", "close": "2330", "id": "a3", "isOpen": true}], 
        "friday": [{"open": "0005", "close": "2330", "id": "a4", "isOpen": true}], 
        "saturday": [{"open": "0005", "close": "2330", "id": "a5", "isOpen": true}], 
        "sunday": [{"open": "0005", "close": "2330", "id": "a6", "isOpen": true}]
        }, 
    "auto_planning": true,
    "is_active": true
}


###
# @name create_job_0

POST {{server_url}}/jobs/  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
    "code":"A2-0",
    "team": {"code": "{{team_code}}"} ,
    "job_type": "visit",
    "auto_planning": false,
    "is_active": true,
    "planning_status": "U",
    "geo_longitude": 103.733, 
    "geo_latitude": 1.309, 
    "requested_start_datetime": "2023-11-13T07:06:40",
    "requested_duration_minutes": 0.5,
    "flex_form_data": {
        "area_code": "A",
        "skills":"TV"
    }
}


###
# @name reset_planning_window

POST {{server_url}}/planner_service/reset_planning_window/   HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{"team_code":  "{{team_code}}"}



###
# @name run_batch_optimizer_all

POST {{server_url}}/planner_service/run_batch_optimizer/   HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
    "team_code": "{{team_code}}" 
}


###
POST {{server_url}}/planner_service/get_env_jobs/  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
    "team_code": "{{team_code}}", 
    "reset_start_datetime": false,
    "active_only":false
}
